POST http://0.0.0.0:8009/inquire

{
    "question": "What are the agents you have access to ?"
}

###
POST http://0.0.0.0:8009/inquire

{
    "question": "what is the latest article on https://aws.amazon.com/blogs/aws?"
}
###

POST http://0.0.0.0:8009/inquire

{
    "question": "What is the square root of the hour?"
}
